version: '3.7'
services:
  backend:
    container_name: api_backend
    restart: unless-stopped
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    command: npm run start:dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  frontend:
    container_name: web_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - backend
  
  mongodb:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'